### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by lili890527** [xuyan0213/script#4]
如下：
今日签到时间：2024-03-12</span><e
今日魔力值：50
连续签到天数：9
今日签到中止

**Comment by xqy0213** [comment]
![009d208b337f931ecdc2b883613d456](https://github.com/xuyan0213/script/assets/49686577/cb7d365b-3a4e-476b-89a7-19e08af8ae01)
重试一下 我这边没问题

**Comment by lili890527** [comment]
查看日志，有显示。今日签到时间：2024-03-13</span><e。感觉是env.js问题。还是一样问题

**Comment by xqy0213** [comment]
签到完成了 但是显示今日签到终止吗?

**Comment by xqy0213** [comment]
> 查看日志，有显示。今日签到时间：2024-03-13<e。感觉是env.js问题。还是一样问题

重新拉一下，增加了PTTIME_UID配置项
